In [8]:
a=int(input("donner un nombre de ligne :")) 
b=int(input("donner un nombre de colone :")) 
c=int(input("donner un nombre de liste :"))
k=np.arange(c).reshape(a,b)
l=k.tolist()
print(l)

donner un nombre de ligne :3
donner un nombre de colone :2
donner un nombre de liste :6
[[0, 1], [2, 3], [4, 5]]


In [2]:
import numpy as np 
array=np.random.uniform(2,10,size=(3,3))
x=np.diagonal(array)
print("your array:",array)
print(x)
print(sum(x))

your array: [[2.66550947 7.29114088 3.66907855]
 [8.72840311 4.97182272 5.79167279]
 [4.0278979  3.20303427 3.53516655]]
[2.66550947 4.97182272 3.53516655]
11.172498736928382


In [8]:
import numpy as np 
e=np.array([[15,2],[3,5]])
x=3
print("the values higher than x;",e[e>x])

the values higher than x; [15  5]


In [9]:
import numpy as np
a=np.array([1,7,6,25])
b=np.array([5,21,15,3])
c=np.array(a+b)
c

array([ 6, 28, 21, 28])

In [35]:
import numpy 
x=[12,35]
x=numpy.mean(x)
print(x)



23.5
